cow:
  image: cow_in_docker
  volumes:
     - ./rc:/usr/local/app/rc
  ports:
          - "7777:7777/tcp"
  environments:
          - "DEBUG=true"
          - "COW_PATH=/usr/local/app/rc"
  restart: always
